Repository pingcap/tidb-ansible, pull requests merged in 2019-12, with the labels that each got.

#1048 update tispark to 2.1.6 (#1043)
  roles/local/tasks/binary_deployment.yml
  roles/local/templates/binary_packages.yml.j2
  roles/tispark/tasks/main.yml
Labels: cherry-pick

#1038 add alert rule for tidb binlog error count
  roles/prometheus/files/tidb.rules.yml
  scripts/tidb.json
Labels: 2.1, cherry-pick

#1028 scripts: support act on for filter metrics (#966)
  scripts/pd.json
Labels: cherry-pick

#1020 check systemd version
  roles/check_system_static/tasks/main.yml
Labels: enhancement, master

#1053 revert config 3.0
  conf/pd.yml
  conf/tidb.yml
  conf/tikv.yml
  roles/pd/vars/default.yml
  roles/tidb/vars/default.yml
  roles/tikv/vars/default.yml
Labels: 3.0

#1056 update version check (#1050)
  rolling_update.yml
Labels: 3.0, cherry-pick

#1057 update version check (#1050)
  rolling_update.yml
Labels: 3.1, cherry-pick

#1060 release tispark-2.1.7 for release-2.1 branch
  roles/local/tasks/binary_deployment.yml
  roles/local/templates/binary_packages.yml.j2
  roles/tispark/tasks/main.yml
Labels: 2.1

#1059 release tispark-2.1.7 for release-3.1 branch
  roles/local/tasks/binary_deployment.yml
  roles/local/templates/binary_packages.yml.j2
  roles/tispark/tasks/main.yml
Labels: 3.1

#1058 release tispark-2.1.7 for release-3.0 branch
  roles/local/tasks/binary_deployment.yml
  roles/local/templates/binary_packages.yml.j2
  roles/tispark/tasks/main.yml
Labels: 3.0

#1065 fix pd role metric for 3.0
  scripts/pd.json
Labels: 3.0, bug

#1066 fix pd role metric for 3.0 (#1065)
  scripts/pd.json
Labels: 3.1, bug, cherry-pick

#1071 tikv_details: speed up grafana display - release-3.0
  scripts/tikv_details.json
Labels: 3.0, cherry-pick, enhancement

#1072 tikv_details: speed up grafana display - release-3.1
  scripts/tikv_details.json
Labels: 3.1, cherry-pick, enhancement

#1075 tikv/conf: change default pessimistic-txn.wake-up-delay-duration
  conf/tikv.yml
  roles/tikv/vars/default.yml
Labels: 3.0, master

#1080 scripts: update the KV metrics on TiDB
  scripts/tidb.json
  scripts/tidb_summary.json
Labels: LGT1

#1079 THP: set disable
  roles/bootstrap/tasks/root_tasks.yml
Labels: enhancement, master

#1082 scripts: update txn metrics
  scripts/overview.json
  scripts/tidb.json
  scripts/tidb_summary.json
Labels: enhancement

#1083 server: add lock duration panel
  scripts/tidb.json
Labels: 3.0

#1085 THP: set disable (#1079)
  roles/bootstrap/tasks/root_tasks.yml
Labels: 3.0, cherry-pick, enhancement

#1086 THP: set disable (#1079)
  roles/bootstrap/tasks/root_tasks.yml
Labels: 3.1, cherry-pick, enhancement

#1076 tikv/conf: change default pessimistic-txn.wake-up-delay-duration
  conf/tikv.yml
  roles/tikv/vars/default.yml
Labels: 3.0, cherry-pick

#1087 release v2.1.19
  inventory.ini
Labels: 2.1
