Repository pingcap/tidb-ansible, pull requests merged in 2019-07, with the labels that each got.

#830 scripts: add some metrics for tidb
  scripts/tidb.json
Labels: LGT1

#838 tispark use 2.1.1 instead of master branch
  roles/local/tasks/binary_deployment.yml
  roles/local/templates/binary_packages.yml.j2
  roles/tispark/tasks/main.yml
Labels: cherry-pick

#839 tispark use 2.1.1 instead of master branch
  roles/local/tasks/binary_deployment.yml
  roles/local/templates/binary_packages.yml.j2
  roles/tispark/tasks/main.yml
Labels: cherry-pick

#844 fix wrong format config file (#829)
  roles/prometheus/templates/prometheus.yml.j2
Labels: cherry-pick

#845 fix wrong format config file (#829)
  roles/prometheus/templates/prometheus.yml.j2
Labels: cherry-pick

#847 grafana: add descriptions for every tidb panel
  scripts/tidb.json
Labels: enhancement

#850 Update tidb.toml.j2 (#849)
  conf/tidb.yml
  roles/tidb/templates/tidb.toml.j2
  roles/tidb/vars/default.yml
Labels: bug, cherry-pick

#853 scripts: add some metrics for tidb (#830)
  scripts/tidb.json
Labels: cherry-pick

#854 add descriptions for every tidb panel (#847)
  scripts/tidb.json
Labels: cherry-pick

#857 update tikv grafana allocator_stats name
  scripts/tikv_details.json
Labels: cherry-pick
