Repository pingcap/tidb-ansible, pull requests merged in 2019-09, with the labels that each got.

#927 update tispark to 2.2.0 (release-2.1)
  roles/local/tasks/binary_deployment.yml
  roles/local/templates/binary_packages.yml.j2
  roles/tispark/tasks/main.yml
Labels: cherry-pick

#932 Update tidb configuration
  conf/tidb.yml
  roles/tidb/vars/default.yml
Labels: bug

#933 Update tidb configuration (#932)
  conf/tidb.yml
  roles/tidb/vars/default.yml
Labels: cherry-pick

#934 Check config before deploy or rolling_update (#917)
  deploy.yml
  excessive_rolling_update.yml
  roles/check_config/tasks/check_pd_config.yml
  roles/check_config/tasks/check_tidb_config.yml
  roles/check_config/tasks/check_tikv_config.yml
  roles/check_config/tasks/main.yml
  rolling_update.yml
Labels: cherry-pick

#938 Add metrics to node_exporter (#907)
  roles/node_exporter/templates/run_node_exporter_binary.sh.j2
  scripts/node.json
Labels: cherry-pick

#937 Update disk space check module
  roles/check_system_dynamic/tasks/main.yml
Labels: bug

#940 Update disk space check module (#937)
  roles/check_system_dynamic/tasks/main.yml
Labels: cherry-pick

#941 Update disk space check module (#937)
  roles/check_system_dynamic/tasks/main.yml
Labels: cherry-pick

#945 Modify perf tools deploying path
  deploy.yml
Labels: enhancement

#946 Add perf tools(3.0)
  deploy.yml
  roles/perf_tools/tasks/main.yml
  scripts/funcslower
  scripts/iosnoop
Labels: cherry-pick

#948 Replace raw module to shell (#947)
  roles/check_config_static/tasks/main.yml
  roles/check_system_static/tasks/main.yml
  roles/pre-ansible/tasks/coreos.yml
  roles/pre-ansible/tasks/main.yml
  roles/pre-ansible/tasks/root_tasks.yml
Labels: cherry-pick

#949 Liubo/remove raw module 3.0
  roles/check_config_static/tasks/main.yml
  roles/check_system_static/tasks/main.yml
  roles/pre-ansible/tasks/coreos.yml
  roles/pre-ansible/tasks/main.yml
  roles/pre-ansible/tasks/root_tasks.yml
Labels: cherry-pick

#954 Remove configuration check and release v2.1.17
  deploy.yml
  inventory.ini
  roles/check_config/tasks/check_pd_config.yml
  roles/check_config/tasks/check_tidb_config.yml
  roles/check_config/tasks/check_tikv_config.yml
  roles/check_config/tasks/main.yml
  rolling_update.yml
Labels: bug

#959 Liubo/update config
  conf/tidb.yml
  roles/tidb/vars/default.yml
Labels: cherry-pick

#960 fix TiDB alert rules
  roles/prometheus/files/tidb.rules.yml
Labels: LGT1, bug

#961 fix TiDB alert rules (#960)
  roles/prometheus/files/tidb.rules.yml
Labels: LGT1, cherry-pick

#962 fix TiDB alert rules (#960)
  roles/prometheus/files/tidb.rules.yml
Labels: LGT1, cherry-pick

#967 Update scripts/grafana-config-copy.py
  scripts/grafana-config-copy.py
Labels: bug

#972 update config check 3.0
  roles/check_config/tasks/check_pd_config.yml
  roles/check_config/tasks/check_tidb_config.yml
  roles/check_config/tasks/check_tikv_config.yml
Labels: cherry-pick

#973 update config check 2.1
  deploy.yml
  roles/check_config/tasks/check_pd_config.yml
  roles/check_config/tasks/check_tidb_config.yml
  roles/check_config/tasks/check_tikv_config.yml
  roles/check_config/tasks/main.yml
  rolling_update.yml
Labels: cherry-pick

#976 tidb: add index speed metric
  scripts/tidb.json
Labels: enhancement

#970 Add inventory check function
  roles/check_config_static/tasks/main.yml
  scripts/inventory_check.py
Labels: enhancement
