Repository pingcap/tidb-ansible, pull requests merged in 2019-11, with the labels that each got.

#1019 remove obsolete config pessimistic txn ttl
  conf/tidb.yml
  roles/tidb/vars/default.yml
Labels: LGT2

#1016 add metrics for batch request
  scripts/tikv_details.json
Labels: enhancement

#1026 config: add gc config (#1018)
  conf/tikv.yml
  roles/tikv/templates/tikv.toml.j2
  roles/tikv/vars/default.yml
Labels: cherry-pick

#1033 tikv: add backup metrics (#1031)
  scripts/tikv_details.json
Labels: cherry-pick

#1032 scripts: update TiDB transaction counter
  scripts/tidb.json
  scripts/tidb_summary.json
Labels: enhancement

#1036 add alert rule for tidb binlog error count (#1005)
  roles/prometheus/files/tidb.rules.yml
  scripts/tidb.json
Labels: cherry-pick

#1035 scripts: update TiDB transaction counter (#1032)
  scripts/tidb.json
  scripts/tidb_summary.json
Labels: cherry-pick

#1034 scripts: update TiDB transaction counter (#1032)
  scripts/tidb.json
  scripts/tidb_summary.json
Labels: cherry-pick

#1037 add alert rule for tidb binlog error count (#1005)
  roles/prometheus/files/tidb.rules.yml
  scripts/tidb.json
Labels: cherry-pick

#1046 tikv: fix backup thread CPU usage
  scripts/tikv_details.json
Labels: cherry-pick
