Repository pingcap/tidb-ansible, pull requests merged in 2020-09, with the labels that each got.

#1346 Added some panels for TiFlash about write stall
  scripts/tiflash_summary.json
Labels: 4.0

#1348 add tiflash encryption metrics (#1347)
  scripts/tiflash_proxy_details.json
Labels: 4.0, cherry-pick

#1350 update spark.tispark.grpc.framesize default value (#1349)
  conf/spark-defaults.yml
Labels: 4.0, cherry-pick

#1351 update spark.tispark.grpc.framesize default value (#1349)
  conf/spark-defaults.yml
Labels: 3.1, cherry-pick

#1352 update spark.tispark.grpc.framesize default value (#1349)
  conf/spark-defaults.yml
Labels: 3.0, cherry-pick

#1354 Add metrics for ApplySnapshot and IngestSST in TiFlash
  scripts/tiflash_summary.json
Labels: 4.0
