Repository pingcap/tidb-ansible, pull requests merged in 2020-02, with the labels that each got.

#1125 Update wrong expression in node.json
  scripts/node.json
Labels: bug, master, monitor

#1132 add lock keys counter panel in tidb transaction tab
  scripts/tidb.json
Labels: 3.0

#1133 add pessimistic retry count panel in tidb transaction tab
  scripts/tidb.json
Labels: 3.0

#1138 [cherry-pick] refactor tiflash config
  conf/tiflash-learner.yml
  conf/tiflash.yml
  roles/tiflash/defaults/main.yml
  roles/tiflash/tasks/main.yml
  roles/tiflash/templates/tiflash.toml.j2
  roles/tiflash/templates/tiflash_learner.toml.j2
  roles/tiflash/vars/tiflash-learner.yml
  roles/tiflash/vars/tiflash.yml
Labels: cherry-pick

#1137 Support multiple monitor nodes
  roles/check_config_static/tasks/main.yml
  roles/grafana/templates/data_source.json.j2
  roles/prometheus/templates/prometheus.yml.j2
  rolling_update_monitor.yml
  scripts/grafana-config-copy.py
  start.yml
Labels: master, monitor, new feature

#1142 Support multiple monitor nodes (#1137)
  roles/check_config_static/tasks/main.yml
  roles/grafana/templates/data_source.json.j2
  roles/prometheus/templates/prometheus.yml.j2
  rolling_update_monitor.yml
  scripts/grafana-config-copy.py
  start.yml
Labels: 4.0, cherry-pick, monitor, new feature

#1143 Support multiple monitor nodes (#1137)
  roles/check_config_static/tasks/main.yml
  roles/grafana/templates/data_source.json.j2
  roles/prometheus/templates/prometheus.yml.j2
  rolling_update_monitor.yml
  scripts/grafana-config-copy.py
  start.yml
Labels: 3.1, cherry-pick, monitor, new feature

#1145 [cherry-pick] tiflash add metrics port (#1144)
  conf/tiflash.yml
  group_vars/tiflash_servers.yml
  roles/tiflash/defaults/main.yml
  roles/tiflash/tasks/main.yml
  roles/tiflash/templates/tiflash.toml.j2
  roles/tiflash/vars/tiflash.yml
Labels: 4.0, cherry-pick

#1147 add tiflash conf in prometheus for tiflash dashboard (#1146)
  roles/prometheus/templates/prometheus.yml.j2
Labels: 4.0, cherry-pick, monitor

#1148 release-3.1: support tiflash
  conf/tiflash-learner.yml
  conf/tiflash.yml
  deploy.yml
  excessive_rolling_update.yml
  group_vars/tiflash_servers.yml
  inventory.ini
  roles/common_dir/tasks/main.yml
  roles/local/tasks/binary_deployment.yml
  roles/local/templates/binary_packages.yml.j2
  roles/prometheus/templates/prometheus.yml.j2
  roles/tiflash/defaults/main.yml
  roles/tiflash/meta/main.yml
  roles/tiflash/tasks/binary_deployment.yml
  roles/tiflash/tasks/main.yml
  roles/tiflash/tasks/supervise_deployment.yml
  roles/tiflash/tasks/systemd_deployment.yml
  roles/tiflash/templates/run_tiflash_binary.sh.j2
  roles/tiflash/templates/tiflash.toml.j2
  roles/tiflash/templates/tiflash_learner.toml.j2
  roles/tiflash/vars/tiflash-learner.yml
  roles/tiflash/vars/tiflash.yml
  rolling_update.yml
  start.yml
  stop.yml
  unsafe_cleanup.yml
Labels: 3.1, cherry-pick, new feature

#1150 Add tiflash dashboard
  excessive_rolling_update.yml
  roles/pd/templates/pd.toml.j2
  rolling_update.yml
  rolling_update_monitor.yml
  scripts/grafana-config-copy.py
  scripts/tiflash_proxy_summary.json
  scripts/tiflash_summary.json
  start.yml
Labels: master, monitor

#1152 Add tiflash dashboard (#1150)
  excessive_rolling_update.yml
  roles/pd/templates/pd.toml.j2
  rolling_update.yml
  rolling_update_monitor.yml
  scripts/grafana-config-copy.py
  scripts/tiflash_proxy_summary.json
  scripts/tiflash_summary.json
  start.yml
Labels: 3.1, cherry-pick, monitor

#1151 Add tiflash dashboard (#1150)
  excessive_rolling_update.yml
  roles/pd/templates/pd.toml.j2
  rolling_update.yml
  rolling_update_monitor.yml
  scripts/grafana-config-copy.py
  scripts/tiflash_proxy_summary.json
  scripts/tiflash_summary.json
  start.yml
Labels: 4.0, cherry-pick, monitor

#1153 remove tiflash_http_port config
  roles/tiflash/templates/tiflash_learner.toml.j2
Labels: master

#1154 [cherry-pick] remove tiflash_http_port config (#1153)
  roles/tiflash/templates/tiflash_learner.toml.j2
Labels: 3.1, cherry-pick

#1155 [cherry-pick] remove tiflash_http_port config (#1153)
  roles/tiflash/templates/tiflash_learner.toml.j2
Labels: 4.0, cherry-pick

#1156 release v3.0.10
  inventory.ini
Labels: 3.0

#1149 scripts: more metrics for lock manager (#1090) (#1114)
  scripts/tikv_details.json
Labels: 3.1, cherry-pick

#1160 add tiflash alert rules & refactor tiflash grafana dashboard (#1158)
  roles/prometheus/files/tiflash.rules.yml
  roles/prometheus/tasks/main.yml
  roles/prometheus/templates/prometheus.yml.j2
  scripts/tiflash_proxy_summary.json
  scripts/tiflash_summary.json
Labels: 4.0, cherry-pick

#1159 add tiflash alert rules & refactor tiflash grafana dashboard (#1158)
  roles/prometheus/files/tiflash.rules.yml
  roles/prometheus/tasks/main.yml
  roles/prometheus/templates/prometheus.yml.j2
  scripts/tiflash_proxy_summary.json
  scripts/tiflash_summary.json
Labels: 3.1, cherry-pick

#1161 roles: remove pd namespace config
  conf/pd.yml
  roles/pd/vars/default.yml
Labels: 3.1

#1165 remove log.file.log-rotate from tidb configuration
  conf/tidb.yml
  roles/tidb/vars/default.yml
Labels: 3.1

#1163 fix 404 url
  roles/check_system_dynamic/tasks/main.yml
  roles/check_system_static/tasks/main.yml
  roles/tikv/tasks/check_filesystem.yml
Labels: bug, master

#1167 fix 404 url (#1163)
  roles/check_system_dynamic/tasks/main.yml
  roles/check_system_static/tasks/main.yml
  roles/tikv/tasks/check_filesystem.yml
Labels: 4.0, bug, cherry-pick

#1168 fix 404 url (#1163)
  roles/check_system_dynamic/tasks/main.yml
  roles/check_system_static/tasks/main.yml
  roles/tikv/tasks/check_filesystem.yml
Labels: 3.1, bug, cherry-pick

#1169 fix 404 url (#1163)
  roles/check_system_dynamic/tasks/main.yml
  roles/check_system_static/tasks/main.yml
  roles/tikv/tasks/check_filesystem.yml
Labels: 3.0, bug, cherry-pick

#1170 fix 404 url (#1163)
  roles/check_system_dynamic/tasks/main.yml
  roles/check_system_static/tasks/main.yml
  roles/tikv/tasks/check_filesystem.yml
Labels: 2.1, bug, cherry-pick

#1166 fix error when wait replication
  start.yml
Labels: bug, master

#1171 fix error when wait replication (#1166)
  start.yml
Labels: 4.0, bug, cherry-pick

#1172 fix error when wait replication (#1166)
  start.yml
Labels: 3.1, bug, cherry-pick

#1173 fix error when wait replication (#1166)
  start.yml
Labels: 3.0, bug, cherry-pick

#1176 add tiflash comment
  inventory.ini
Labels: master

#1178 add tiflash comment (#1176)
  inventory.ini
Labels: 3.1, cherry-pick

#1179 add tiflash comment (#1176)
  inventory.ini
Labels: 4.0, cherry-pick

#1177 TiFlash: support multiple data dir
  filter_plugins/tags.py
  roles/tiflash/defaults/main.yml
  roles/tiflash/tasks/main.yml
  roles/tiflash/templates/tiflash.toml.j2
  roles/tiflash/templates/tiflash_learner.toml.j2
  unsafe_cleanup.yml
  unsafe_cleanup_data.yml
Labels: master, new feature

#1181 TiFlash: support multiple data dir (#1177)
  filter_plugins/tags.py
  roles/tiflash/defaults/main.yml
  roles/tiflash/tasks/main.yml
  roles/tiflash/templates/tiflash.toml.j2
  roles/tiflash/templates/tiflash_learner.toml.j2
  unsafe_cleanup.yml
  unsafe_cleanup_data.yml
Labels: 4.0, cherry-pick

#1182 TiFlash: support multiple data dir (#1177)
  filter_plugins/tags.py
  roles/tiflash/defaults/main.yml
  roles/tiflash/tasks/main.yml
  roles/tiflash/templates/tiflash.toml.j2
  roles/tiflash/templates/tiflash_learner.toml.j2
  unsafe_cleanup.yml
  unsafe_cleanup_data.yml
Labels: 3.1, cherry-pick

#1180 support unified read pool (#1112)
  conf/tikv.yml
  roles/tikv/templates/tikv.toml.j2
  roles/tikv/vars/default.yml
  scripts/tikv_details.json
  scripts/tikv_trouble_shooting.json
Labels: 4.0, cherry-pick

#1183 Modify create_users.yml. (#1041)
  create_users.yml
Labels: 3.1, cherry-pick

#1184 Modify create_users.yml. (#1041)
  create_users.yml
Labels: 3.0, cherry-pick

#1185 Modify create_users.yml. (#1041)
  create_users.yml
Labels: 2.1, cherry-pick

#1186 release-4.0: update download
  roles/local/tasks/binary_deployment.yml
Labels: 4.0
