Repository pingcap/tidb-ansible, pull requests merged in 2020-04, with the labels that each got.

#1236 cherry pick sync unified read pool default configurations with tikv#7234 (#1232)
  conf/tikv.yml
  roles/tikv/vars/default.yml
Labels: 4.0, cherry-pick

#1250 support download and deploy tiflash
  roles/local/tasks/binary_deployment.yml
Labels: 4.0

#1251 fix init dashboard
  rolling_update.yml
Labels: 4.0, bug

#1252 update tiflash grafana
  scripts/blackbox_exporter.json
  scripts/overview.json
  scripts/tiflash_summary.json
Labels: master, monitor

#1260 fix tikv conf template (#1259)
  conf/tikv.yml
Labels: 4.0, cherry-pick

#1269 set madvdontneed=1 to shrink RSS after GC
  roles/tidb/templates/run_tidb_binary.sh.j2
Labels: 2.1, cherry-pick, enhancement

#1268 set madvdontneed=1 to shrink RSS after GC
  roles/tidb/templates/run_tidb_binary.sh.j2
Labels: 3.1, cherry-pick, enhancement

#1267 set madvdontneed=1 to shrink RSS after GC
  roles/tidb/templates/run_tidb_binary.sh.j2
Labels: enhancement

#1273 change task comment
  roles/local/tasks/main.yml
  roles/pre-ansible/tasks/coreos.yml
Labels: master

#1274 change task comment (#1273)
  roles/local/tasks/main.yml
  roles/pre-ansible/tasks/coreos.yml
Labels: 4.0, cherry-pick

#1275 change task comment (#1273)
  roles/local/tasks/main.yml
  roles/pre-ansible/tasks/coreos.yml
Labels: 3.1, cherry-pick

#1276 change task comment (#1273)
  roles/local/tasks/main.yml
  roles/pre-ansible/tasks/coreos.yml
Labels: 3.0, cherry-pick

#1277 change task comment (#1273)
  roles/local/tasks/main.yml
  roles/pre-ansible/tasks/coreos.yml
Labels: 2.1, cherry-pick

#1280 Show TiFlash storage metrics in grafana (#1278)
  scripts/tiflash_summary.json
Labels: 3.1, cherry-pick

#1281 Show TiFlash storage metrics in grafana (#1278)
  scripts/tiflash_summary.json
Labels: 4.0, cherry-pick

#1283 rename variable name
  roles/local/tasks/binary_deployment.yml
  roles/local/tasks/main.yml
  roles/local/templates/binary_packages.yml.j2
  roles/pre-ansible/defaults/main.yml
  roles/pre-ansible/tasks/coreos.yml
Labels: master

#1284 rename variable name (#1283)
  roles/local/tasks/binary_deployment.yml
  roles/local/tasks/main.yml
  roles/local/templates/binary_packages.yml.j2
  roles/pre-ansible/defaults/main.yml
  roles/pre-ansible/tasks/coreos.yml
Labels: 4.0, cherry-pick

#1285 rename variable name 3.1
  roles/local/tasks/binary_deployment.yml
  roles/local/tasks/main.yml
  roles/local/templates/binary_packages.yml.j2
  roles/pre-ansible/defaults/main.yml
  roles/pre-ansible/tasks/coreos.yml
Labels: 3.1, cherry-pick

#1286 rename variable name 3.0
  roles/local/tasks/binary_deployment.yml
  roles/local/tasks/main.yml
  roles/local/templates/binary_packages.yml.j2
  roles/pre-ansible/defaults/main.yml
  roles/pre-ansible/tasks/coreos.yml
Labels: 3.0, cherry-pick

#1287 rename variable name 2.1
  roles/local/tasks/binary_deployment.yml
  roles/local/tasks/main.yml
  roles/local/templates/binary_packages.yml.j2
  roles/pre-ansible/defaults/main.yml
  roles/pre-ansible/tasks/coreos.yml
Labels: 2.1, cherry-pick

#1289 update api return code
  common_tasks/add_evict_leader_scheduler.yml
Labels: bug, master

#1290 update api return code (#1289)
  common_tasks/add_evict_leader_scheduler.yml
Labels: 4.0, bug, cherry-pick
