Repository pingcap/tidb-ansible, pull requests merged in 2020-03, with the labels that each got.

#1190 multiple monitor: fix deploy error
  roles/grafana/templates/data_source.json.j2
Labels: bug, master, monitor

#1191 multiple monitor: fix deploy error (#1190)
  roles/grafana/templates/data_source.json.j2
Labels: 4.0, bug, cherry-pick, monitor

#1192 multiple monitor: fix deploy error (#1190)
  roles/grafana/templates/data_source.json.j2
Labels: 3.1, bug, cherry-pick, monitor

#1193 TiDB: add a variable to control the max index length
  conf/tidb.yml
  roles/tidb/vars/default.yml
Labels: master

#1194 TiDB: add a variable to control the max index length (#1193)
  conf/tidb.yml
  roles/tidb/vars/default.yml
Labels: 3.0, cherry-pick

#1195 Support Prometheus in for dashboard topology
  roles/dashboard_topo/templates/init_dashboard_topo.sh.j2
  scripts/dashboard_topo.py
Labels: master

#1198 support multiple monitor node
  roles/check_config_static/tasks/main.yml
  roles/grafana/templates/data_source.json.j2
  roles/prometheus/templates/prometheus.yml.j2
  rolling_update_monitor.yml
  scripts/grafana-config-copy.py
  start.yml
Labels: 3.0, cherry-pick, monitor

#1199 support multiple monitor node
  roles/check_config_static/tasks/main.yml
  roles/grafana/templates/data_source.json.j2
  roles/prometheus/templates/prometheus.yml.j2
  rolling_update_monitor.yml
  scripts/grafana-config-copy.py
  start.yml
Labels: 2.1, cherry-pick, monitor

#1197 support arm
  deploy.yml
  inventory.ini
  roles/check_system_static/tasks/main.yml
  roles/local/tasks/binary_deployment.yml
  roles/local/templates/binary_packages.yml.j2
  roles/local/templates/common_packages.yml.j2
  rolling_update.yml
  scripts/check/epollexclusive-amd64
  scripts/check/epollexclusive-arm64
Labels: master, new feature

#1205 change default version
  inventory.ini
Labels: master

#1196 release-4.0: Support Inject cluster topology information for am and grafana to etcd in pd
  deploy.yml
  excessive_rolling_update.yml
  roles/dashboard_topo/tasks/main.yml
  roles/dashboard_topo/templates/init_dashboard_topo.sh.j2
  rolling_update.yml
  scripts/dashboard_topo.py
  start.yml
Labels: 4.0, cherry-pick

#1204 release-4.0: support arm
  deploy.yml
  inventory.ini
  roles/check_system_static/tasks/main.yml
  roles/local/tasks/binary_deployment.yml
  roles/local/templates/binary_packages.yml.j2
  roles/local/templates/common_packages.yml.j2
  rolling_update.yml
  scripts/check/epollexclusive-amd64
  scripts/check/epollexclusive-arm64
Labels: 4.0, cherry-pick, new feature

#1206 update excessive rolling
  excessive_rolling_update.yml
  rolling_update.yml
Labels: master

#1207 update excessive rolling (#1206)
  excessive_rolling_update.yml
  rolling_update.yml
Labels: 4.0, cherry-pick

#1209 conf, roles: add the config of alter-primary-key
  conf/tidb.yml
  roles/tidb/vars/default.yml
Labels: master

#1210 conf, roles: add the config of alter-primary-key (#1209)
  conf/tidb.yml
  roles/tidb/vars/default.yml
Labels: 4.0

#1211 conf, roles: add the config of alter-primary-key (#1209)
  conf/tidb.yml
  roles/tidb/vars/default.yml
Labels: 3.0

#1212 release-4.0 tidb: add a variable to control the max index length
  conf/tidb.yml
  roles/tidb/vars/default.yml
Labels: 4.0, cherry-pick

#1214 conf, roles: add the config of alter-primary-key(#1209)
  conf/tidb.yml
  roles/tidb/vars/default.yml
Labels: 3.1, cherry-pick

#1222 update tiflash storage engine
  conf/tiflash.yml
  roles/tiflash/vars/tiflash.yml
Labels: master

#1224 update tiflash storage engine (#1222)
  conf/tiflash.yml
  roles/tiflash/vars/tiflash.yml
Labels: 4.0, cherry-pick

#1223 update tiflash storage engine (#1222)
  conf/tiflash.yml
  roles/tiflash/vars/tiflash.yml
Labels: 3.1, cherry-pick

#1217 conf, roles: add the config of auto-random, expression and new-collation
  conf/tidb.yml
  roles/tidb/templates/tidb.toml.j2
  roles/tidb/vars/default.yml
Labels: 4.0

#1230 epoll: update comment
  roles/check_system_static/tasks/main.yml
  scripts/check/epoll_chk.cc
  scripts/check/epollexclusive-amd64
  scripts/check/epollexclusive-arm64
Labels: 4.0, cherry-pick

#1233 add tiflash metrics tiflash_storage_write_amplification
  scripts/tiflash_summary.json
Labels: master

#1234 add tiflash metrics tiflash_storage_write_amplification (#1233)
  scripts/tiflash_summary.json
Labels: 3.1, cherry-pick

#1235 add tiflash metrics tiflash_storage_write_amplification (#1233)
  scripts/tiflash_summary.json
Labels: 4.0, cherry-pick

#1231 config, roles: add config of server-version.
  conf/tidb.yml
  roles/tidb/vars/default.yml
Labels: master

#1232 sync unified read pool default configurations with tikv#7234
  conf/tikv.yml
  roles/tikv/vars/default.yml
Labels: 4.0

#1237 update dashboard init (#1226)
  deploy.yml
  excessive_rolling_update.yml
  roles/dashboard_topo/tasks/main.yml
  rolling_update.yml
  start.yml
Labels: 4.0, cherry-pick

#1239 use sudo privileges to create tiflash data_dir (#1227)
  roles/tiflash/tasks/main.yml
Labels: 4.0, cherry-pick

#1242 use sudo privileges to create tiflash data_dir (#1227)
  roles/tiflash/tasks/main.yml
Labels: 3.1, cherry-pick

#1238 config, roles: add config of server-version (#1231)
  conf/tidb.yml
  roles/tidb/vars/default.yml
Labels: 3.0, cherry-pick

#1240 config, roles: add config of server-version (#1231)
  conf/tidb.yml
  roles/tidb/vars/default.yml
Labels: 3.1, cherry-pick

#1241 config, roles: add config of server-version (#1231)
  conf/tidb.yml
  roles/tidb/vars/default.yml
Labels: 4.0, cherry-pick

#1243 epoll: update comment
  roles/check_system_static/tasks/main.yml
  scripts/check/epoll_chk.cc
Labels: 3.1

#1245 conf, roles: add the config of auto-random, expression and new-collation(#1217)
  conf/tidb.yml
  roles/tidb/templates/tidb.toml.j2
  roles/tidb/vars/default.yml
Labels: 4.0, cherry-pick

#1246 conf, roles: add the config of auto-random (#1217)
  conf/tidb.yml
  roles/tidb/templates/tidb.toml.j2
  roles/tidb/vars/default.yml
Labels: 3.1
