Repository pingcap/tidb-ansible, pull requests merged in 2020-07, with the labels that each got.

#1323 Add details dashboard for TiFlash-Proxy (#1321)
  rolling_update_monitor.yml
  scripts/grafana-config-copy.py
  scripts/tiflash_proxy_details.json
  scripts/tiflash_summary.json
  start.yml
Labels: 3.1

#1322 Add details dashboard for TiFlash-Proxy (#1321)
  rolling_update_monitor.yml
  scripts/grafana-config-copy.py
  scripts/tiflash_proxy_details.json
  scripts/tiflash_summary.json
  start.yml
Labels: 4.0

#1325 update tiflash dashboard (#1324)
  scripts/tiflash_proxy_details.json
  scripts/tiflash_proxy_summary.json
Labels: 4.0, cherry-pick

#1326 update tiflash dashboard (#1324)
  scripts/tiflash_proxy_details.json
  scripts/tiflash_proxy_summary.json
Labels: 3.1, cherry-pick

#1314 fix tidb conf format
  conf/tidb.yml
Labels: LGT1

#1327 fix tidb conf format (#1314)
  conf/tidb.yml
Labels: 4.0, cherry-pick

#1328 update pd config
  conf/pd.yml
  roles/pd/vars/default.yml
Labels: bug, master

#1329 update pd config (#1328)
  conf/pd.yml
  roles/pd/vars/default.yml
Labels: 4.0, bug, cherry-pick

#1330 fix config check
  roles/check_config_pd/tasks/main.yml
  roles/check_config_tidb/tasks/main.yml
  roles/check_config_tikv/tasks/main.yml
Labels: bug, master

#1331 update config check (#1330)
  roles/check_config_pd/tasks/main.yml
  roles/check_config_tidb/tasks/main.yml
  roles/check_config_tikv/tasks/main.yml
Labels: 4.0, cherry-pick

#1332 Liubo/fix config check 3.1
  roles/check_config_pd/tasks/main.yml
  roles/check_config_tidb/tasks/main.yml
  roles/check_config_tikv/tasks/main.yml
Labels: 3.1, cherry-pick

#1333 update config check (#1330)
  roles/check_config_pd/tasks/main.yml
  roles/check_config_tidb/tasks/main.yml
  roles/check_config_tikv/tasks/main.yml
Labels: 3.0, cherry-pick

#1335 fix bug when enable tls
  common_tasks/get_pd_name_tls.yml
Labels: bug, master

#1336 fix bug when enable tls (#1335)
  common_tasks/get_pd_name_tls.yml
Labels: 4.0, bug, cherry-pick

#1337 Liubo/fix tls 3.1
  common_tasks/get_pd_name_tls.yml
Labels: 3.1, bug, cherry-pick

#1338 fix bug when enable tls (#1335)
  common_tasks/get_pd_name_tls.yml
Labels: 3.0, bug, cherry-pick

#1339 fix bug when enable tls (#1335)
  common_tasks/get_pd_name_tls.yml
Labels: 2.1, bug, cherry-pick

#1340 update config check (#1330)
  roles/check_config_pd/tasks/main.yml
  roles/check_config_tidb/tasks/main.yml
  roles/check_config_tikv/tasks/main.yml
Labels: 2.1, bug, cherry-pick

#1341 update the default value of oom-action(tidb)
  conf/tidb.yml
  roles/tidb/vars/default.yml
Labels: master
