Repository pingcap/tidb-ansible, pull requests merged in 2020-05, with the labels that each got.

#1292 TiFlash Grafana: Read Index Count -> Read Index Rate (#1291)
  scripts/tiflash_summary.json
Labels: 3.1, cherry-pick

#1293 TiFlash Grafana: Read Index Count -> Read Index Rate (#1291)
  scripts/tiflash_summary.json
Labels: 4.0, cherry-pick

#1299 update doc link
  roles/check_system_dynamic/tasks/main.yml
  roles/check_system_static/tasks/main.yml
  roles/tikv/tasks/check_filesystem.yml
Labels: bug, master

#1300 update doc link (#1299)
  roles/check_system_dynamic/tasks/main.yml
  roles/check_system_static/tasks/main.yml
  roles/tikv/tasks/check_filesystem.yml
Labels: 4.0, bug, cherry-pick

#1301 update doc link (#1299)
  roles/check_system_dynamic/tasks/main.yml
  roles/check_system_static/tasks/main.yml
  roles/tikv/tasks/check_filesystem.yml
Labels: 3.1, bug, cherry-pick

#1302 update doc link (#1299)
  roles/check_system_dynamic/tasks/main.yml
  roles/check_system_static/tasks/main.yml
  roles/tikv/tasks/check_filesystem.yml
Labels: 3.0, bug, cherry-pick

#1303 update tikv config template for security features (#1298)
  conf/tikv.yml
  roles/tikv/templates/tikv.toml.j2
  roles/tikv/vars/default.yml
Labels: 4.0, cherry-pick

#1307 Fix tikv config check failure on deploy (#1306)
  conf/tikv.yml
  roles/tikv/vars/default.yml
Labels: 4.0, bug, cherry-pick
