Repository pingcap/tidb-ansible, pull requests merged in 2020-01, with the labels that each got.

#1092 scripts: update transaction TTL related metrics for tidb grafana
  scripts/tidb.json
Labels: enhancement

#1064 scripts/tidb: add panel for ddl add index progress
  scripts/tidb.json
Labels: master

#1104 Add create directory automatically (#1103)
  conf/tidb-lightning.yml
  conf/tikv-importer.yml
  roles/tidb_lightning/defaults/main.yml
  roles/tidb_lightning/tasks/main.yml
  roles/tikv_importer/defaults/main.yml
  roles/tikv_importer/tasks/main.yml
Labels: 3.1, cherry-pick, enhancement

#1105 Add create directory automatically (#1103)
  conf/tidb-lightning.yml
  conf/tikv-importer.yml
  roles/tidb_lightning/defaults/main.yml
  roles/tidb_lightning/tasks/main.yml
  roles/tikv_importer/defaults/main.yml
  roles/tikv_importer/tasks/main.yml
Labels: 3.0, cherry-pick, enhancement

#1101 tikv-conf: update default pessimistic-txn config
  conf/tikv.yml
  roles/tikv/vars/default.yml
Labels: 3.0, 3.1, master

#1107 reduce lightning config and optimize `tikv_importer_port` config
  conf/tidb-lightning.yml
  group_vars/all.yml
  group_vars/importer_server.yml
  roles/tidb_lightning/tasks/main.yml
  roles/tidb_lightning/templates/tidb-lightning.toml.j2
  roles/tidb_lightning/vars/tidb-lightning.yml
Labels: bug, master

#1108 merge from master
  conf/tidb-lightning.yml
  group_vars/all.yml
  group_vars/importer_server.yml
  roles/tidb_lightning/tasks/main.yml
  roles/tidb_lightning/templates/tidb-lightning.toml.j2
  roles/tidb_lightning/vars/tidb-lightning.yml
Labels: 3.1, bug, cherry-pick

#1109 merge from master (#1108)
  conf/tidb-lightning.yml
  group_vars/all.yml
  group_vars/importer_server.yml
  roles/tidb_lightning/tasks/main.yml
  roles/tidb_lightning/templates/tidb-lightning.toml.j2
  roles/tidb_lightning/vars/tidb-lightning.yml
Labels: 3.0, bug, cherry-pick

#1110 update lightning
  conf/tidb-lightning.yml
  conf/tikv-importer.yml
  group_vars/all.yml
  group_vars/importer_server.yml
  roles/tidb_lightning/defaults/main.yml
  roles/tidb_lightning/tasks/main.yml
  roles/tidb_lightning/templates/tidb-lightning.toml.j2
  roles/tidb_lightning/vars/tidb-lightning.yml
  roles/tikv_importer/defaults/main.yml
  roles/tikv_importer/tasks/main.yml
Labels: 2.1, bug, cherry-pick

#1090 scripts: more metrics for lock manager
  scripts/tikv_details.json
Labels: 3.0, 3.1

#1115 tikv-conf: update default pessimistic-txn config (#1101)
  conf/tikv.yml
  roles/tikv/vars/default.yml
Labels: 3.0, cherry-pick

#1116 change tikv config
  conf/tikv.yml
  roles/tikv/vars/default.yml
Labels: 3.1, cherry-pick

#1114 scripts: more metrics for lock manager (#1090)
  scripts/tikv_details.json
Labels: 3.0, cherry-pick

#1117 release v3.1.0-beta.1
  inventory.ini
Labels: 3.1

#1118 Get version from variable for tiflash
  roles/local/tasks/binary_deployment.yml
  roles/local/templates/binary_packages.yml.j2
  roles/tiflash/vars/tiflash-user.yml
Labels: enhancement

#1111 change tikv config template
  conf/tikv.yml
  roles/tikv/vars/default.yml
Labels: master

#1120 release v3.0.9
  inventory.ini
Labels: 3.0

#1121 fix get current pd leader error when rolling update pd (#1081)
  common_tasks/transfer_pd_leader.yml
Labels: 3.0, cherry-pick

#1122 fix get current pd leader error when rolling update pd (#1081)
  common_tasks/transfer_pd_leader.yml
Labels: 3.1, cherry-pick

#1119 Support Tiflash
  conf/tiflash-learner.yml
  conf/tiflash.yml
  deploy.yml
  excessive_rolling_update.yml
  group_vars/tiflash_servers.yml
  inventory.ini
  roles/common_dir/tasks/main.yml
  roles/local/tasks/binary_deployment.yml
  roles/local/templates/binary_packages.yml.j2
  roles/tiflash/defaults/main.yml
  roles/tiflash/meta/main.yml
  roles/tiflash/tasks/binary_deployment.yml
  roles/tiflash/tasks/main.yml
  roles/tiflash/tasks/supervise_deployment.yml
  roles/tiflash/tasks/systemd_deployment.yml
  roles/tiflash/templates/run_tiflash_binary.sh.j2
  roles/tiflash/templates/tiflash.toml.j2
  roles/tiflash/templates/tiflash_learner.toml.j2
  roles/tiflash/vars/tiflash-learner.yml
  roles/tiflash/vars/tiflash.yml
  rolling_update.yml
  start.yml
  stop.yml
  unsafe_cleanup.yml
Labels: master, new feature
