Repository pingcap/tidb-ansible, pull requests merged in 2020-06, with the labels that each got.

#1308 fix panel datasource name
  scripts/tidb.json
Labels: 3.0, bug

#1310 add metric for perf-context
  scripts/tikv_details.json
Labels: 4.0

#1316 fix disk metrics (#1315)
  scripts/disk_performance.json
Labels: 4.0, cherry-pick

#1317 fix disk metrics (#1315)
  scripts/disk_performance.json
Labels: 3.1, cherry-pick

#1318 fix disk metrics (#1315)
  scripts/disk_performance.json
Labels: 3.0, cherry-pick
